project/diseaseDetection/diseaseDetection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    #path('', include('userManagement.urls')),

    #path('accounts/', include('allauth.urls')),

    path('admin/', admin.site.urls),
    path('', home_view, name="home_view"),
    path('account', include('account.urls', namespace='account')),
    path('posts', include('posts.urls', namespace='posts')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/diseaseDetection/posts/urls.py
from django.urls import path

from .views import post_comment_loves_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('/', post_comment_loves_view, name="main-post-view"),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

project/diseaseDetection/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from account.models import Profile

# Create your models here.


class Post(models.Model):
    content = models.TextField(blank=False,  max_length=1000)
    images = models.ImageField(upload_to='posts', validators=[
                               FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(
        Profile, default=None, related_name='likes', blank=True)
    created = models.DateTimeField(auto_now=True)
    update = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return str(self.content)

    def num_likes(self):

        return self.liked.all().count()

    # num of comment

    def num_comments(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ('-created',)


# for comment model


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    created = models.DateTimeField(auto_now=True)
    update = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


LOVE_CHOCIES = (
    ('like', 'Like'),
    ('unlike', 'Unlike'),

)


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LOVE_CHOCIES, max_length=8, )
    created = models.DateTimeField(auto_now=True)
    update = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

project/diseaseDetection/posts/forms.py
from django import forms

from .models import Post, Comment


class PostModelForm(forms.ModelForm):

    content  = forms.CharField(widget=forms.Textarea(attrs={'rows':2 }))
    class Meta:
        model = Post
        fields = ('content', 'images')


class CommentModelForm(forms.ModelForm):
    body  = forms.CharField(label='',widget=forms.Textarea(attrs={'placeholder':'Add a comment...' , 'rows':1}))
    class Meta:
        model = Comment
        fields = ('body',)

project/diseaseDetection/posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Post, Like, Comment

from account.models import Profile

from . forms import PostModelForm, CommentModelForm

from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def post_comment_loves_view(request):
    ps = Post.objects.all()

    #cs = Comment.objects.all()

    # post and comment form
    # initialization
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_added = False
    comment_added = False

    profile = Profile.objects.get(user=request.user)

    # if 'submit_p_form' in request.POST:
    #     print(request.POST)
    #     p_form = PostModelForm(request.POST, request.FILES)
    #     if p_form.is_valid():
    #         instance = p_form.save(commit=False)
    #         instance.author = profile
    #         instance.save()
    #         p_form = PostModelForm()
    #         post_added = True

    if 'submit_c_form' in request.POST:

        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()

            c_form = CommentModelForm()
            comment_added = True

    context = {
        'ps': ps,
        'profile': profile,
        # 'cs': cs,
        'p_form': p_form,
        'c_form': c_form,
        'post_added': post_added,
        'comment_added': comment_added,
    }
    return render(request, 'posts/main.html', context)


def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(
            user=profile, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        else:
            like.value = 'Like'

            post_obj.save()
            like.save()

        data = {
            'value': like.value,
            'likes': post_obj.liked.all().count()
        }
        return JsonResponse(data, safe=False)

    return redirect('posts:main-post-view')


class PostDeleteView(DeleteView):
    model = Post
    template_name = "posts/confirm_del.html"
    success_url = reverse_lazy('posts:main-post-view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if obj.author.user == self.request.user:
            messages.warning(self.request, 'must be author of the post')
        return obj


class PostUpdateView(UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:main-post-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "must be author of the post")
            return super().form_invalid(form)

project/diseaseDetection/posts/templates/posts/confirm_del.html
{%extends 'base.html' %}

{% block title%}

Delete Post
{% endblock title%}

{% block content%}

    <div class="ui segment">
        <h3>
            Delete Post
        </h3>
        
        <form method="POST">
            {%csrf_token%}
            <h4>
                Are you sure want to delete post?
            </h4>

            <button type="submit" class="ui negative button">
                yes
            </button>
            <button class="ui button primary">
                <a href="/post">No</a> 
            </button>

        </form>
        
            
        
    </div>
{% endblock content%}

project/diseaseDetection/posts/templates/posts/main.html
{% extends 'base.html' %}
{% block title %}
Post

{% endblock title %}
{% block content%}

<div class="ui grid " style="margin-top:10px;">
    
    <div class="row">
        <div class="ten wide column ">
            
            {% for obj in ps %}


            <div class="ui fluid card">
                <div class="content">
                    <div class="right floated meta">
                        <div class="ui grid">
                            
                                <i class="ellipsis vertical icon display-menu "></i>
                            
                            <div class="content-menu">
                                {% ifequal request.user obj.author.user %}
                                    <a href="{% url 'posts:post-delete' obj.pk %}"><button class="ui button bwhitelg">delete</button></a>
                                    <a href="{% url 'posts:post-update' obj.pk %}"><button class="ui button bwhitelg">update</button></a>

                                {%endifequal%}
                                <span class="post_hide"> remove the post</span>
                            </div>
                        </div>

                    </div>
                    <img class="ui avatar image" src="{{obj.author.avatar.url}}" alt="">
                    {{obj.author.user}}  - {{obj.created|timesince}} ago
                
                </div>
                <div class="content">
                    <p>{{obj.content}}</p>
                    
                    <div class="right floated">
                        <form action="{% url 'posts:like-post-view' %}" method="POST" class="like-form" id={{obj.id}}>
                            {% csrf_token %}
                            <input type="hidden" name='post_id' value={{obj.id}}>
                            
                            <button class="ui button like-btn{{obj.id}} " type="submit">
                                {% if profile not in obj.liked.all %}
                                    <span> Like</span>
                                <!-- <span class="liked-heart">
                                        <i class="heart outline icon " style="font-size:20px !important"></i>
                                        
                                </span> -->
                                {% else %} 
                                <span > Unlike</span>
                                    <!-- <span class="unliked-heart">
                                        <i class="heart icon" style="color:red !important; font-size:20px"></i>
                                        
                                </span> -->
                                {% endif %}
                            </button>        
                                    
                               
                            
                            <div class="ui grid">
                                <div class="column">
                                    <div class="like-count{{obj.id}}">{{obj.num_likes}}</div>

                                </div>
                                <div class="column">
                                    Likes
                                </div>

                            </div>
                        </form> 
                    </div>
                    <div>
                        <i class="comment icon"></i>
                        <span>{{obj.num_comments}} comments</span>
                    </div>
                </div>

                <div class="extra content">
                    <div class="mb-5">

                    </div>
                    <div class="comment-box">
                        {% if obj.comment_set.all%}

                        {%  for c in obj.comment_set.all %}
                            <div class="ui segment mb-5">
                                <img  class ="ui avatar image"src={{c.user.avatar.url}}>
                                <span>{{c.user.user}} - {{obj.created|timesince}} ago</span>
                                <div class="mt-5">{{c.body}}</div>
                            </div>
                        {% endfor %}

                        {%endif%}
                    </div>
                </div>
                <div class="content">
                    {% if comment_added %}
                        <div class="ui green message">comment added Successfully</div>
                    {% endif %}
                    <form action="" method="POST" class="ui form comment-form" id={{obj.id}}>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        <input type = "text" name="comment" value={obj.id}>
                        <p class="comment-form{{obj.id}}">{{c_form}}</p>
                        <button type="submit" class="ui primary button  " name="submit_c_form">Comment</button>
                    </form>

                </div>
                
            </div>
                
            {% endfor %}
        
        </div>
        <div class="five wide column">
            {% if post_added %}
            <div class="ui green message">Post added Successfully</div>
            {% endif %}
            <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                {% csrf_token %}

                {{p_form.as_p}}

                <button class="ui button positive" type="submit" name="submit_p_form">
                    update post
                </button>
            
            </form>
        </div>

    </div>

</div>

<style>
    .button:hover .icon{
        
            color:red !important;
        
    }
    .content-menu{
        display:none;
    }
    
    .display-menu{
        cursor: pointer;
    }
</style>





{% endblock content%}

project/diseaseDetection/posts/templates/posts/update.html
{% extends 'base.html'%}

{% block title%}

update Post

{% endblock title%}


{%block content%}

    <div class="ui segment">
        <h3 style="text-align:center">
            Update Post
        </h3>
        <form action="" method="POST" class="ui from" enctype="multipart/form-data">

            {% csrf_token%}
            {{form.as_p}}
            <button class="ui button primary mt-5" type="submit">Update</button>

        </form>

    </div>

{%endblock content%}